import Head from 'next/head'
import HeaderComponent from "../../components/Header";
import FooterComponent from "../../components/Footer";
import GamesComponent from '../../components/Game'
import styles from "../../styles/Home.module.css";
import ScrollComponent from "../../components/Scroll";

export default function Games() {
    return (
        <div className={styles.container}>

            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <HeaderComponent/>

            <GamesComponent/>

            <FooterComponent/>

            <ScrollComponent />

        </div>
    )
}